---
title: "process-ROS-data"
output: html_document
date: "2024-01-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## aquafluor data processing

Using input cell counts from processing FCM data, process Aquafluor data from 914 & 874 nitrogen-temperature colimitation experiments.

```{r read_ros}
af_data=read.csv("../data/914/aquafluor_914.csv")
conc_data=read.csv("../data/914/914_all_conc.csv")

af_data_merged = af_data %>% dplyr::mutate(Date = as.Date(Date, format="%m/%d/%Y"),
                                             n_conc=as.character(n_conc)) %>%
  dplyr::left_join(conc_data %>% dplyr::mutate(Date = as.Date(Date,format="%Y-%m-%d"),
                                               n_conc=as.character(n_conc)),
                   by=c("Date","rep","n_conc","temp_c"))
```

## Plot AF data

```{r}
ggplot(af_data_merged) + 
  geom_point(aes(x = Date, y = chl..total., col=n_conc)) + 
  geom_line(aes(x = Date, y = chl..total., col=n_conc, group=paste0(n_conc,rep))) + 
  facet_wrap(~temp_c,scales="free_y",nrow=2) + ylab("total chlorophyll fluorescence") + 
  theme_bw(base_size=12)
```


```{r}
ggplot(af_data_merged) + 
  geom_point(aes(x = Date, y = F0/Fm, col=n_conc)) + 
  geom_line(aes(x = Date, y = F0/Fm, col=n_conc, group=paste0(n_conc,rep))) + 
  facet_wrap(~temp_c,scales="free_y",nrow=2) + ylab("Fv/Fm") + 
  theme_bw(base_size=12)
```